name: Docker Image CI

on:
  push:
    branches: [ "docker-github-action-testing" ]
  pull_request:
    branches: [ "docker-github-action-testing" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HBase Repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        # This action ensures Docker Compose is installed and available
        uses: docker/setup-compose-action@v2

      - name: Check container status (optional)
        run: docker-compose ps

      # - name: Start Docker Clusters
      #   run: |
      #     docker-compose -f docker-compose.test.yml up -d
      #     echo "Waiting for HBase clusters to initialize..."
      #     # Self-healing check: Wait for Master UI to return 200 OK
      #     until $(curl --output /dev/null --silent --head --fail http://localhost:16010); do
      #       printf '.'
      #       sleep 5
      #     done
      #     echo "Clusters are up!"

      - name: Clean up
        # This step runs automatically as a post-hook in many actions,
        # but you can also explicitly call it.
        run: docker-compose down
